---

# Workflow for ansible-lint of a role

name: ansible-lint of the role testrole01

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**'
  workflow_dispatch:
    branches:
      - main
      - dev
    paths:
      - '**'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@main

      - name: Display the path
        run: pwd

      - name: Display the directory tree
        run: tree -Ls 2

      - name: Set up Python 3
        uses: actions/setup-python@main
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          pip3 install ansible==9.1.0
          pip3 install ansible-compat==4.1.11
          pip3 install ansible-core==2.16.2
          pip3 install ansible-lint==6.22.2

      - name: Run ansible-lint
        working-directory: /home/runner/work/testrole01/testrole01
        run: ansible-lint
