---

# Workflow for ansible-lint of a role

name: ansible-lint of the role testrole01

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**'
  workflow_dispatch:
    branches:
      - main
      - dev
    paths:
      - '**'

jobs:
  ansible-lint:
    name: call-ansible-lint-with-role
    steps:
      - name: 'berndfinger/testrole01/.github/workflows/ansible-lint-reusable-workflow.yml@main'
        uses: berndfinger/testrole01/.github/workflows/ansible-lint-reusable-workflow.yml@main
        with:
          role: testrole01
